#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver
- name: Update apt repository
  apt:
    update_cache: yes

- name: Install Apache, PHP en PHP-MySQL
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Start en enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
